# -*- coding: utf-8 -*-
"""
生成 90 条 MySQL 数据一致性校验脚本（基于 campus_bazaar.sql 真实表结构）。
按 9 个域分组输出到 03_数据校验与报表测试/MySQL校验脚本/<域>/DB-CK-###_标题.sql
每个脚本的判定标准：正常数据下应返回 0 行（第 90 条为快照汇总，返回 1 行）。
运行：python gen_mysql_checks.py
"""
import os, re

BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                    "03_数据校验与报表测试", "MySQL校验脚本")

# 每条校验: (域, 标题, SQL主体, 判定说明)
CHECKS = [
# ============ 01 基础数据（001-010） ============
("01_基础数据", "分类名重复",
 "SELECT id, name, COUNT(*) c FROM cb_category GROUP BY name HAVING c > 1;",
 "cb_category.name 唯一约束，不应出现重复分类名"),
("01_基础数据", "分类名超长",
 "SELECT id, name, CHAR_LENGTH(name) L FROM cb_category WHERE CHAR_LENGTH(name) > 20;",
 "分类名 VARCHAR(20)，长度不得超过20"),
("01_基础数据", "分类排序字段缺失",
 "SELECT id, name FROM cb_category WHERE sort IS NULL;",
 "sort 应有默认值0，不允许空"),
("01_基础数据", "分类表无主键冲突",
 "SELECT id, COUNT(*) c FROM cb_category GROUP BY id HAVING c > 1;",
 "id 为主键，不应重复"),
("01_基础数据", "用户名重复",
 "SELECT id, username, COUNT(*) c FROM cb_user GROUP BY username HAVING c > 1;",
 "cb_user.username 唯一约束，不应重复"),
("01_基础数据", "用户名超长",
 "SELECT id, username, CHAR_LENGTH(username) L FROM cb_user WHERE CHAR_LENGTH(username) > 30;",
 "用户名 VARCHAR(30)，不得超过30字符"),
("01_基础数据", "昵称为空",
 "SELECT id, username FROM cb_user WHERE nickname IS NULL OR nickname = '';",
 "昵称必填，不允许空"),
("01_基础数据", "密码为空",
 "SELECT id, username FROM cb_user WHERE password IS NULL OR password = '';",
 "密码必填，不允许空"),
("01_基础数据", "密码非MD5格式",
 "SELECT id, username, password FROM cb_user WHERE password NOT REGEXP '^[0-9a-f]{32}$';",
 "密码应为32位MD5十六进制密文，否则存在明文存储风险"),
("01_基础数据", "用户注册时间缺失",
 "SELECT id, username FROM cb_user WHERE created_at IS NULL;",
 "created_at 必填"),
# ============ 02 用户一致性（011-020） ============
("02_用户一致性", "手机号格式非法",
 "SELECT id, username, phone FROM cb_user WHERE phone IS NOT NULL AND phone NOT REGEXP '^[0-9]{11}$';",
 "手机号应为11位数字"),
("02_用户一致性", "学校字段超长",
 "SELECT id, username, CHAR_LENGTH(school) L FROM cb_user WHERE school IS NOT NULL AND CHAR_LENGTH(school) > 50;",
 "学校字段 VARCHAR(50)"),
("02_用户一致性", "信用分越界",
 "SELECT id, username, credit_score FROM cb_user WHERE credit_score < 0 OR credit_score > 200;",
 "信用分范围 0-200"),
("02_用户一致性", "角色值非法",
 "SELECT id, username, role FROM cb_user WHERE role NOT IN (0, 1);",
 "role 取值 0-普通用户 1-管理员"),
("02_用户一致性", "状态值非法",
 "SELECT id, username, status FROM cb_user WHERE status NOT IN (0, 1);",
 "status 取值 0-禁用 1-正常"),
("02_用户一致性", "头像URL超长",
 "SELECT id, username, CHAR_LENGTH(avatar) L FROM cb_user WHERE avatar IS NOT NULL AND CHAR_LENGTH(avatar) > 255;",
 "头像URL VARCHAR(255)"),
("02_用户一致性", "商品卖家外键悬空",
 "SELECT i.id item_id, i.seller_id FROM cb_item i WHERE NOT EXISTS (SELECT 1 FROM cb_user u WHERE u.id = i.seller_id);",
 "商品 seller_id 必须对应真实用户"),
("02_用户一致性", "订单买家外键悬空",
 "SELECT o.id order_id, o.buyer_id FROM cb_order o WHERE NOT EXISTS (SELECT 1 FROM cb_user u WHERE u.id = o.buyer_id);",
 "订单 buyer_id 必须对应真实用户"),
("02_用户一致性", "订单卖家外键悬空",
 "SELECT o.id order_id, o.seller_id FROM cb_order o WHERE NOT EXISTS (SELECT 1 FROM cb_user u WHERE u.id = o.seller_id);",
 "订单 seller_id 必须对应真实用户"),
("02_用户一致性", "禁用用户仍有在售商品",
 "SELECT i.id item_id, i.seller_id, u.username FROM cb_item i JOIN cb_user u ON u.id = i.seller_id WHERE u.status = 0 AND i.status = 1;",
 "被禁用用户不应存在在售商品，需业务确认处理策略"),
# ============ 03 商品数据完整性（021-032） ============
("03_商品数据完整性", "商品标题为空",
 "SELECT id, seller_id FROM cb_item WHERE title IS NULL OR title = '';",
 "标题必填"),
("03_商品数据完整性", "商品标题超长",
 "SELECT id, CHAR_LENGTH(title) L FROM cb_item WHERE CHAR_LENGTH(title) > 50;",
 "标题 VARCHAR(50)"),
("03_商品数据完整性", "商品价格为空",
 "SELECT id, title FROM cb_item WHERE price IS NULL;",
 "价格必填"),
("03_商品数据完整性", "商品价格非正",
 "SELECT id, title, price FROM cb_item WHERE price <= 0;",
 "价格必须大于0"),
("03_商品数据完整性", "商品原价越界",
 "SELECT id, title, original_price FROM cb_item WHERE original_price IS NOT NULL AND (original_price <= 0 OR original_price > 99999999.99);",
 "原价应为正数且不超过 DECIMAL(10,2) 上限"),
("03_商品数据完整性", "原价低于现价",
 "SELECT id, title, price, original_price FROM cb_item WHERE original_price IS NOT NULL AND original_price < price;",
 "业务上原价一般不低于现价，出现此情况需人工确认"),
("03_商品数据完整性", "商品分类外键悬空",
 "SELECT i.id, i.category_id FROM cb_item i WHERE NOT EXISTS (SELECT 1 FROM cb_category c WHERE c.id = i.category_id);",
 "category_id 必须对应真实分类"),
("03_商品数据完整性", "商品卖家外键悬空",
 "SELECT i.id, i.seller_id FROM cb_item i WHERE NOT EXISTS (SELECT 1 FROM cb_user u WHERE u.id = i.seller_id);",
 "seller_id 必须对应真实用户"),
("03_商品数据完整性", "商品成色值非法",
 "SELECT id, condition_level FROM cb_item WHERE condition_level NOT BETWEEN 1 AND 5;",
 "成色取值 1-5"),
("03_商品数据完整性", "商品状态值非法",
 "SELECT id, status FROM cb_item WHERE status NOT IN (0, 1, 2, 3, 4);",
 "状态取值 0待审核/1在售/2锁定/3已售/4下架"),
("03_商品数据完整性", "商品图片超长",
 "SELECT id, CHAR_LENGTH(images) L FROM cb_item WHERE images IS NOT NULL AND CHAR_LENGTH(images) > 500;",
 "images VARCHAR(500)"),
("03_商品数据完整性", "浏览收藏数为负",
 "SELECT id, view_count, fav_count FROM cb_item WHERE view_count < 0 OR fav_count < 0;",
 "view_count/fav_count 不应为负"),
# ============ 04 收藏一致性（033-040） ============
("04_收藏一致性", "收藏用户外键悬空",
 "SELECT f.id, f.user_id FROM cb_favorite f WHERE NOT EXISTS (SELECT 1 FROM cb_user u WHERE u.id = f.user_id);",
 "收藏 user_id 必须对应真实用户"),
("04_收藏一致性", "收藏商品外键悬空",
 "SELECT f.id, f.item_id FROM cb_favorite f WHERE NOT EXISTS (SELECT 1 FROM cb_item it WHERE it.id = f.item_id);",
 "收藏 item_id 必须对应真实商品"),
("04_收藏一致性", "同一用户重复收藏同一商品",
 "SELECT user_id, item_id, COUNT(*) c FROM cb_favorite GROUP BY user_id, item_id HAVING c > 1;",
 "(user_id,item_id) 唯一约束，不应重复收藏"),
("04_收藏一致性", "收藏数与fav_count不一致",
 "SELECT it.id, it.fav_count, t.actual FROM cb_item it LEFT JOIN (SELECT item_id, COUNT(*) actual FROM cb_favorite GROUP BY item_id) t ON t.item_id = it.id WHERE it.fav_count <> COALESCE(t.actual, 0);",
 "商品 fav_count 应与收藏表实际数量一致"),
("04_收藏一致性", "收藏已删除商品",
 "SELECT f.id, f.item_id FROM cb_favorite f LEFT JOIN cb_item it ON it.id = f.item_id WHERE it.id IS NULL;",
 "收藏的商品必须存在"),
("04_收藏一致性", "收藏时间缺失",
 "SELECT id, user_id, item_id FROM cb_favorite WHERE created_at IS NULL;",
 "收藏时间必填"),
("04_收藏一致性", "收藏主键冲突",
 "SELECT id, COUNT(*) c FROM cb_favorite GROUP BY id HAVING c > 1;",
 "id 主键不应重复"),
("04_收藏一致性", "收藏不存在商品",
 "SELECT f.id, f.item_id FROM cb_favorite f WHERE NOT EXISTS (SELECT 1 FROM cb_item it WHERE it.id = f.item_id);",
 "收藏商品必须存在（外键级校验）"),
# ============ 05 订单一致性（041-056） ============
("05_订单一致性", "订单号为空",
 "SELECT id FROM cb_order WHERE order_no IS NULL OR order_no = '';",
 "订单号必填"),
("05_订单一致性", "订单号超长",
 "SELECT id, CHAR_LENGTH(order_no) L FROM cb_order WHERE CHAR_LENGTH(order_no) > 32;",
 "订单号 VARCHAR(32)"),
("05_订单一致性", "订单号重复",
 "SELECT order_no, COUNT(*) c FROM cb_order GROUP BY order_no HAVING c > 1;",
 "订单号唯一，不应重复"),
("05_订单一致性", "订单买家外键悬空",
 "SELECT o.id, o.buyer_id FROM cb_order o WHERE NOT EXISTS (SELECT 1 FROM cb_user u WHERE u.id = o.buyer_id);",
 "buyer_id 必须对应真实用户"),
("05_订单一致性", "订单卖家外键悬空",
 "SELECT o.id, o.seller_id FROM cb_order o WHERE NOT EXISTS (SELECT 1 FROM cb_user u WHERE u.id = o.seller_id);",
 "seller_id 必须对应真实用户"),
("05_订单一致性", "订单商品外键悬空",
 "SELECT o.id, o.item_id FROM cb_order o WHERE NOT EXISTS (SELECT 1 FROM cb_item it WHERE it.id = o.item_id);",
 "item_id 必须对应真实商品"),
("05_订单一致性", "自买自卖订单",
 "SELECT id, order_no, buyer_id, seller_id FROM cb_order WHERE buyer_id = seller_id;",
 "买卖双方不应为同一人"),
("05_订单一致性", "订单价格为空",
 "SELECT id, order_no FROM cb_order WHERE price IS NULL;",
 "成交价必填"),
("05_订单一致性", "订单价格为负",
 "SELECT id, order_no, price FROM cb_order WHERE price < 0;",
 "成交价不应为负"),
("05_订单一致性", "订单价与商品价不一致",
 "SELECT o.id, o.order_no, o.price order_price, it.price item_price FROM cb_order o JOIN cb_item it ON it.id = o.item_id WHERE o.price <> it.price;",
 "订单成交价应与商品当前价一致（交易中商品不可改价）"),
("05_订单一致性", "订单卖家与商品卖家不一致",
 "SELECT o.id, o.order_no, o.seller_id, it.seller_id item_seller FROM cb_order o JOIN cb_item it ON it.id = o.item_id WHERE o.seller_id <> it.seller_id;",
 "订单 seller_id 应与商品 seller_id 一致"),
("05_订单一致性", "订单留言超长",
 "SELECT id, CHAR_LENGTH(message) L FROM cb_order WHERE message IS NOT NULL AND CHAR_LENGTH(message) > 200;",
 "message VARCHAR(200)"),
("05_订单一致性", "交易地点超长",
 "SELECT id, CHAR_LENGTH(meet_place) L FROM cb_order WHERE meet_place IS NOT NULL AND CHAR_LENGTH(meet_place) > 100;",
 "meet_place VARCHAR(100)"),
("05_订单一致性", "订单状态值非法",
 "SELECT id, order_no, status FROM cb_order WHERE status NOT IN (0, 1, 2, 3);",
 "状态取值 0待确认/1已确认/2已完成/3已取消"),
("05_订单一致性", "待确认订单缺下单时间",
 "SELECT id, order_no FROM cb_order WHERE status = 0 AND created_at IS NULL;",
 "created_at 必填"),
("05_订单一致性", "已确认订单缺确认时间",
 "SELECT id, order_no FROM cb_order WHERE status = 1 AND confirmed_at IS NULL;",
 "已确认订单应记录 confirmed_at"),
# ============ 06 交易状态一致性（057-068） ============
("06_交易状态一致性", "已售商品无已完成订单",
 "SELECT i.id, i.status FROM cb_item i WHERE i.status = 3 AND NOT EXISTS (SELECT 1 FROM cb_order o WHERE o.item_id = i.id AND o.status = 2);",
 "商品已售(status=3)必须存在对应已完成订单"),
("06_交易状态一致性", "锁定商品无有效订单",
 "SELECT i.id, i.status FROM cb_item i WHERE i.status = 2 AND NOT EXISTS (SELECT 1 FROM cb_order o WHERE o.item_id = i.id AND o.status IN (0,1));",
 "商品锁定(status=2)必须存在待确认或已确认订单"),
("06_交易状态一致性", "已完成订单商品非已售",
 "SELECT o.id, o.order_no, o.status, i.status item_status FROM cb_order o JOIN cb_item i ON i.id = o.item_id WHERE o.status = 2 AND i.status <> 3;",
 "订单完成(status=2)时商品应同步为已售(status=3)"),
("06_交易状态一致性", "待确认订单商品非锁定",
 "SELECT o.id, o.order_no, i.status FROM cb_order o JOIN cb_item i ON i.id = o.item_id WHERE o.status = 0 AND i.status <> 2;",
 "订单待确认(status=0)时商品应为锁定(status=2)"),
("06_交易状态一致性", "已确认订单商品非锁定",
 "SELECT o.id, o.order_no, i.status FROM cb_order o JOIN cb_item i ON i.id = o.item_id WHERE o.status = 1 AND i.status <> 2;",
 "订单已确认(status=1)时商品应为锁定(status=2)"),
("06_交易状态一致性", "已取消订单商品仍锁定",
 "SELECT o.id, o.order_no, i.status FROM cb_order o JOIN cb_item i ON i.id = o.item_id WHERE o.status = 3 AND i.status = 2;",
 "订单取消(status=3)后商品应解锁，不得遗留锁定"),
("06_交易状态一致性", "同一商品多条有效订单",
 "SELECT item_id, COUNT(*) c FROM cb_order WHERE status IN (0,1,2) GROUP BY item_id HAVING c > 1;",
 "同一商品同时只允许一条有效订单（防重复购买）"),
("06_交易状态一致性", "取消订单仍为有效交易",
 "SELECT id, order_no FROM cb_order WHERE status = 3 AND confirmed_at IS NOT NULL AND finished_at IS NOT NULL;",
 "已取消订单不应同时带有完成流转记录"),
("06_交易状态一致性", "确认时间早于下单时间",
 "SELECT id, order_no, created_at, confirmed_at FROM cb_order WHERE confirmed_at IS NOT NULL AND confirmed_at < created_at;",
 "confirmed_at 不应早于 created_at"),
("06_交易状态一致性", "完成时间早于确认时间",
 "SELECT id, order_no, confirmed_at, finished_at FROM cb_order WHERE finished_at IS NOT NULL AND confirmed_at IS NOT NULL AND finished_at < confirmed_at;",
 "finished_at 不应早于 confirmed_at"),
("06_交易状态一致性", "订单完成时间缺失",
 "SELECT id, order_no FROM cb_order WHERE status = 2 AND finished_at IS NULL;",
 "已完成订单应记录 finished_at"),
("06_交易状态一致性", "无有效订单的商品状态异常",
 "SELECT i.id, i.status FROM cb_item i WHERE i.status NOT IN (0,4) AND NOT EXISTS (SELECT 1 FROM cb_order o WHERE o.item_id = i.id);",
 "非待审核/下架商品应存在关联订单"),
# ============ 07 留言一致性（069-074） ============
("07_留言一致性", "留言内容为空",
 "SELECT id, item_id, user_id FROM cb_comment WHERE content IS NULL OR content = '';",
 "留言内容必填"),
("07_留言一致性", "留言内容超长",
 "SELECT id, CHAR_LENGTH(content) L FROM cb_comment WHERE CHAR_LENGTH(content) > 200;",
 "content VARCHAR(200)"),
("07_留言一致性", "留言商品外键悬空",
 "SELECT c.id, c.item_id FROM cb_comment c WHERE NOT EXISTS (SELECT 1 FROM cb_item it WHERE it.id = c.item_id);",
 "留言 item_id 必须对应真实商品"),
("07_留言一致性", "留言用户外键悬空",
 "SELECT c.id, c.user_id FROM cb_comment c WHERE NOT EXISTS (SELECT 1 FROM cb_user u WHERE u.id = c.user_id);",
 "留言 user_id 必须对应真实用户"),
("07_留言一致性", "回复指向不存在留言",
 "SELECT c.id, c.reply_id FROM cb_comment c WHERE c.reply_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM cb_comment p WHERE p.id = c.reply_id);",
 "reply_id 必须指向存在的留言"),
("07_留言一致性", "留言时间缺失",
 "SELECT id FROM cb_comment WHERE created_at IS NULL;",
 "created_at 必填"),
# ============ 08 评价一致性（075-082） ============
("08_评价一致性", "评价订单外键悬空",
 "SELECT r.id, r.order_id FROM cb_review r WHERE NOT EXISTS (SELECT 1 FROM cb_order o WHERE o.id = r.order_id);",
 "评价 order_id 必须对应真实订单"),
("08_评价一致性", "评价者外键悬空",
 "SELECT r.id, r.reviewer_id FROM cb_review r WHERE NOT EXISTS (SELECT 1 FROM cb_user u WHERE u.id = r.reviewer_id);",
 "评价者 reviewer_id 必须对应真实用户"),
("08_评价一致性", "被评价者外键悬空",
 "SELECT r.id, r.reviewee_id FROM cb_review r WHERE NOT EXISTS (SELECT 1 FROM cb_user u WHERE u.id = r.reviewee_id);",
 "被评价者 reviewee_id 必须对应真实用户"),
("08_评价一致性", "评分非法",
 "SELECT id, order_id, score FROM cb_review WHERE score NOT BETWEEN 1 AND 5;",
 "评分范围 1-5"),
("08_评价一致性", "评分为空",
 "SELECT id, order_id FROM cb_review WHERE score IS NULL;",
 "评分必填"),
("08_评价一致性", "一单一评违反",
 "SELECT order_id, COUNT(*) c FROM cb_review GROUP BY order_id HAVING c > 1;",
 "同一订单至多一条评价（order_id 唯一约束）"),
("08_评价一致性", "评价内容超长",
 "SELECT id, CHAR_LENGTH(content) L FROM cb_review WHERE content IS NOT NULL AND CHAR_LENGTH(content) > 300;",
 "content VARCHAR(300)"),
("08_评价一致性", "评价订单非已完成",
 "SELECT r.id, r.order_id, o.status FROM cb_review r JOIN cb_order o ON o.id = r.order_id WHERE o.status <> 2;",
 "评价应仅针对已完成交易(status=2)的订单"),
# ============ 09 跨域综合校验（083-090） ============
("09_跨域综合校验", "订单-商品-卖家三方一致性",
 "SELECT o.id order_id, o.order_no, o.buyer_id, o.seller_id, it.seller_id item_seller, o.price, it.price item_price FROM cb_order o JOIN cb_item it ON it.id = o.item_id WHERE o.seller_id <> it.seller_id OR o.price <> it.price;",
 "订单、商品、卖家三者关键字段应一致"),
("09_跨域综合校验", "收藏-商品-用户三方关联",
 "SELECT f.id FROM cb_favorite f LEFT JOIN cb_user u ON u.id = f.user_id LEFT JOIN cb_item it ON it.id = f.item_id WHERE u.id IS NULL OR it.id IS NULL;",
 "收藏记录的买卖双方关联必须完整"),
("09_跨域综合校验", "商品状态与订单状态全量对照",
 "SELECT i.id item_id, i.status item_status, o.id order_id, o.status order_status FROM cb_item i LEFT JOIN cb_order o ON o.item_id = i.id AND o.status IN (0,1,2) ORDER BY i.id;",
 "全量核对商品状态与订单状态的联动关系（人工复核清单）"),
("09_跨域综合校验", "已完成交易缺评价",
 "SELECT o.id, o.order_no FROM cb_order o WHERE o.status = 2 AND NOT EXISTS (SELECT 1 FROM cb_review rv WHERE rv.order_id = o.id);",
 "按一单一评规则，已完成交易应存在评价"),
("09_跨域综合校验", "卖家信用分与评价联动核查",
 "SELECT u.id seller_id, u.username, u.credit_score, t.avg_score, t.cnt FROM cb_user u LEFT JOIN (SELECT reviewee_id, ROUND(AVG(score),2) avg_score, COUNT(*) cnt FROM cb_review GROUP BY reviewee_id) t ON t.reviewee_id = u.id WHERE t.cnt > 0 AND (u.credit_score - 100) <> 0;",
 "卖家信用分应与历史评价联动（人工确认计分规则）"),
("09_跨域综合校验", "用户有效订单数与订单表一致",
 "SELECT u.id user_id, u.username FROM cb_user u LEFT JOIN cb_order o ON (o.buyer_id = u.id OR o.seller_id = u.id) WHERE o.id IS NULL AND u.role = 0;",
 "普通用户应至少能通过订单表检索到其交易（关注无交易用户）"),
("09_跨域综合校验", "六表外键完整性总检",
 "SELECT 'cb_item->seller' t, COUNT(*) bad FROM cb_item i WHERE NOT EXISTS (SELECT 1 FROM cb_user u WHERE u.id=i.seller_id) UNION ALL SELECT 'cb_order->buyer', COUNT(*) FROM cb_order o WHERE NOT EXISTS (SELECT 1 FROM cb_user u WHERE u.id=o.buyer_id) UNION ALL SELECT 'cb_order->item', COUNT(*) FROM cb_order o WHERE NOT EXISTS (SELECT 1 FROM cb_item it WHERE it.id=o.item_id) UNION ALL SELECT 'cb_comment->item', COUNT(*) FROM cb_comment c WHERE NOT EXISTS (SELECT 1 FROM cb_item it WHERE it.id=c.item_id) UNION ALL SELECT 'cb_comment->user', COUNT(*) FROM cb_comment c WHERE NOT EXISTS (SELECT 1 FROM cb_user u WHERE u.id=c.user_id) UNION ALL SELECT 'cb_favorite->user', COUNT(*) FROM cb_favorite f WHERE NOT EXISTS (SELECT 1 FROM cb_user u WHERE u.id=f.user_id) UNION ALL SELECT 'cb_favorite->item', COUNT(*) FROM cb_favorite f WHERE NOT EXISTS (SELECT 1 FROM cb_item it WHERE it.id=f.item_id) UNION ALL SELECT 'cb_review->order', COUNT(*) FROM cb_review r WHERE NOT EXISTS (SELECT 1 FROM cb_order o WHERE o.id=r.order_id);",
 "全表外键完整性总检，各域悬空记录数应为0"),
("09_跨域综合校验", "核心数据快照汇总",
 "SELECT (SELECT COUNT(*) FROM cb_user) users, (SELECT COUNT(*) FROM cb_category) categories, (SELECT COUNT(*) FROM cb_item) items, (SELECT COUNT(*) FROM cb_order) orders, (SELECT COUNT(*) FROM cb_favorite) favorites, (SELECT COUNT(*) FROM cb_comment) comments, (SELECT COUNT(*) FROM cb_review) reviews;",
 "数据快照：返回1行汇总计数，用于与前端/报表核对"),
]

assert len(CHECKS) == 90, "校验脚本数量错误: %d" % len(CHECKS)

def safe_name(s):
    return re.sub(r'[\\/:*?"<>|]', '_', s)

HEADER = """-- ============================================================
-- Campus Bazaar 数据一致性校验脚本
-- 校验编号：DB-CK-%03d    所属域：%s
-- 校验目标：%s
-- 判定标准：%s
-- 执行方式：mysql -uroot -p < 本文件，或在客户端执行（USE campus_bazaar）
-- ============================================================
USE campus_bazaar;

"""

for i, (domain, title, sql, note) in enumerate(CHECKS, 1):
    folder = os.path.join(BASE, domain)
    os.makedirs(folder, exist_ok=True)
    fname = "DB-CK-%03d_%s.sql" % (i, safe_name(title))
    content = HEADER % (i, domain, title, note) + sql + "\n"
    with open(os.path.join(folder, fname), "w", encoding="utf-8") as f:
        f.write(content)

# 生成执行入口脚本（全量运行）
all_in = ["-- 全量执行入口：一键运行全部 90 条校验脚本", "USE campus_bazaar;\n"]
for i, (domain, title, sql, note) in enumerate(CHECKS, 1):
    all_in.append("-- ---------- DB-CK-%03d %s：%s ----------" % (i, title, note))
    all_in.append(sql)
    all_in.append("")
with open(os.path.join(BASE, "00_全部校验一键执行.sql"), "w", encoding="utf-8") as f:
    f.write("\n".join(all_in))

print("生成完成：共 %d 条校验脚本" % len(CHECKS))
from collections import Counter
print("域分布:", dict(Counter(c[0] for c in CHECKS)))
